"""initial migration

Revision ID: 3163141b01b6
Revises: ae6f5c7f4c57
Create Date: 2026-04-08 07:58:33.769878
"""
from alembic import op
import sqlalchemy as sa


revision = '3163141b01b6'
down_revision = 'ae6f5c7f4c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
